### ISSUE TITLE
Add block scanner configuration

### ISSUE THREAD

**Issue by solomondefi-dev** [SolomonDefi/solomon-monorepo#1]
The block scanner should be configurable via code (for library use), and via environment (for cli use).

### Tasks
Add configuration properties with validation/normalization:

- ETH network
- ETH RPC provider
- Block scanner start (block number or latest)
- Contracts to watch (address + abi)
- Able to start scanning from a configurable block number

**Comment by apolkingg8** [comment]
Move it to the backlog, since it's easier to work on this after the watcher service works.

**Comment by beefho67** [comment]
Actions to take on events (point to template from env? or only allow from code/app initialization?) should be separated into a spike
