### ISSUE TITLE
Setting up contract e2e environment

### ISSUE THREAD

**Issue by apolkingg8** [SolomonDefi/solomon-monorepo#116]
**User story**: As a developer, I want the contract service e2e test to be part of contracts app, so that contract service e2e test can be trigged from contracts app and detects any malfunctions of a dev or staging environment or a simulation.

**Scenario 1**: Contract service e2e test

- **Given**: Contract e2e env is set up within contracts app folder

- **And**:  Contract e2e env is set up against a simulation

- **When**: Contract service e2e is triggered from contracts app

- **Then**: It detects any malfunctions, failures, or service down for the contract service

**Comment by beefho67** [comment]
Per discussion with @jtse0 , some scirpts or configs should be developed first for this issue in order to make [#24](https://app.zenhub.com/workspace/o/solomondefi/solomon-monorepo/issues/24) happen

**Comment by beefho67** [comment]
Per discussion with @jtse0 , the scope of this issue can be covered by #161 and #24 so close this one.
