### ISSUE TITLE
Event webhooks

### ISSUE THREAD

**Issue by kelvin-wong** [SolomonDefi/solomon-monorepo#118]
To simplify the webhook structure combines https://github.com/solomondefi/solomon-monorepo/issues/85, https://github.com/solomondefi/solomon-monorepo/issues/86, and https://github.com/solomondefi/solomon-monorepo/issues/88. There are a few suggestions that could consider,

### Namespacing event types ###
For example, `dispute.preorder.created` for the dispute, `payment.preorder.paid` for payment transaction. The benefits of namespacing event types are that they could be more organized and systematic to be processed. Namespace separates events into different groups. It could be easier for indexing and searching too.
Ref: [stripe](https://stripe.com/docs/api/webhook_endpoints/update#update_webhook_endpoint-enabled_events) [paypal](https://developer.paypal.com/docs/api-basics/notifications/webhooks/event-names/#v2)

### Rename party attributes ###
The current spec for the party attributes are `"party1", "party2"`. In terms of law, those parties in a dispute could be directional. So `plaintiff`(commonly used in law), `applicant`, `claimant`, `requester` could be identified as the party who raised the dispute. `respondent`, `defendant`(commonly used in law), `responder` could be identified as the party who responsible for the dispute.

### Message id ###
A unique message id could be included in the message so a random id could lower the risk of replay attacks and the message would not process twice.

https://github.com/solomondefi/solomon-monorepo/issues/85
```json
{
  "id": "<uuid>",
  "type": "payment.<preorder|escrow|chargeback>.created",
  "party1": "<eth-address>",
  "party2": "<eth-address>",
  "contract": "<eth-address>",
  "judgeContract": "<eth-address>",
  "token": "<eth-address>",
  "discount": 0-100,
  "ethPaid": "<double>"
}
```

https://github.com/solomondefi/solomon-monorepo/issues/86
```json
{
  "id": "<uuid>",
  "type": "dispute.<preorder|escrow|chargeback>.created",
  "party1": "<eth-address>",
  "party2": "<eth-address>",
  "contract": "<eth-address>",
  "judgeContract": "<eth-address>"
}
```

https://github.com/solomondefi/solomon-monorepo/issues/88
```json
{
  "id": "<uuid>",
  "type": "evidence.<preorder|escrow|chargeback>.submitted",
  "party1": "<eth-address>",
  "party2": "<eth-address>",
  "contract": "<eth-address>",
  "judgeContract": "<eth-address>",
  "evidenceUrl": "<url>",
  "submitter": "<party1/party2 eth-address>"
}
```

**Comment by solomondefi-dev** [comment]
I agree on namespacing, this seems like a reasonable idea in general.

I agree that the names are too generic, they should be different depending on the type of contract. `party1` and `party2` comes from the contract implementation, where preorder, chargeback, and escrow contracts share the same base class for emitting events and storing variables. The preorder and chargeback contracts have helper functions:
```
    function buyer() public view returns (address) {
        return _party1;
    }

    function merchant() public view returns (address) {
        return _party2;
    }
```
and the escrow contract just uses `_party1` and `_party2` directly. We can adjust to make this clearer, maybe the contracts can emit more specific events, or we can have a translation layer in the watcher.
