### ISSUE TITLE
Optimize docker build

### ISSUE THREAD

**Issue by kelvin-wong** [SolomonDefi/solomon-monorepo#125]
Split from https://github.com/SolomonDefi/solomon-monorepo/issues/109
> Problem 3: Python images are slow to build

### Cause of slow build ####
From the logs on building Docker images using skaffold. There are 2 main time-consuming processes. They are PNPM package installation and Poetry package installation.

#### Make use of PNPM workspace ####
PNPM could define dependencies for different packages in the monorepo. The way it works is similar to our implementation on `subset.config.js`. The main difference is that the PNPM workspace shares a single `node_modules` for all packages. It will save a lot of time on downloading packages/building packages.
https://pnpm.io/workspaces
@solomondefi-dev could look into this.

#### Extract base build stage for Python apps #####
The current base build stage for each Python apps is duplicated. We could extract it into another image and save some build time.
Another potential optimization could be a similar workflow like PNPM workspace as Poetry cache packages in `.cache` folder by default, the cached packages could be shared across different Python apps.

**Comment by solomondefi-dev** [comment]
Closing this since the task is completed as originally defined. Will add an icebox issue for exploring other base images.
