### ISSUE TITLE
Handling of dispute vote encryption

### ISSUE THREAD

**Issue by jtse0** [SolomonDefi/solomon-monorepo#138]
Votes are currently open and unencrypted, however there is a need to keep the votes encrypted so that voters don't know how others are voting.  The method of encryption and how everything will be handled will be detailed further in this ticket before implementation.

**Comment by solomondefi-dev** [comment]
It is probably acceptable for either party to know the current status of the vote, we only need to ensure the jurors don't have access to that information.

One option could be to:
- Generate a secret key on the backend when the dispute begins.
- Email the key to buyer & merchant
  - Include a magic link to the frontend that shows the status of the vote and sets up the tx to reveal/withdraw the result (via MetaMask)
- Per juror, combine the key with some info (address/index/etc) and hash. This is what they submit for `true`
- Generate a random string, this is what they submit for `false`
- Email jurors with vote options and magic links for setting up `true` and `false` votes (via MetaMask, on the page where the evidence is displayed).
- Decrypting is done by either the buyer or merchant submitting their key. The contract iterates through the jurors and checks the votes by doing the same combination as above to create the juror keys.
  - Buyer & merchant can always view the vote status without making a transaction

I may have missed something, but something like this should work - let me know if you can think of any simplifications. The main problem is going to be gas cost, but that's an issue no matter what.
