### ISSUE TITLE
Pin @typechain/ethers-v5 version to 7.x.x

### ISSUE THREAD

**Issue by apolkingg8** [SolomonDefi/solomon-monorepo#139]
Release note: https://github.com/dethcrypto/TypeChain/releases/tag/%40typechain%2Fethers-v5%408.0.0
> Generate types to .ts files instead of .d.ts in Ethers v5 and Web3.js targets

This change causes typescript error (https://github.com/SolomonDefi/solomon-monorepo/runs/4067333580?check_suite_focus=true). Pin the version to 7.x.x until it's resolved.

**Comment by beefho67** [comment]
Pin the version to 7.2.0 via 00caca851a01948cf77853df83301e4cc364d0b5

**Comment by solomondefi-dev** [comment]
@apolkingg8 Is this one possible to solve now? It's better if we can avoid pinning to older dependencies.
