### ISSUE TITLE
Update computation method for staker rewards

### ISSUE THREAD

**Issue by jtse0** [SolomonDefi/solomon-monorepo#145]
As mentioned in issue #123 - calculation for staker rewards should take into account the holdings of the user.  Formula will be updated to: `(staked SLM / total Staked SLM) * reward pool * reward percentage`

Each user holding and total holdings will be recorded in the Staker contracts.

**Comment by solomondefi-dev** [comment]
This will need some slight clarification, it may be necessary to add a constant modifier or other formula adjustment in order to avoid depleting the reward pool too quickly.

**Comment by jtse0** [comment]
Sorry I actually also updated the formula to include a reward percentage for each payment.  We will input a certain `reward percentage` each payment which will be multiplied by the `reward pool` each time and then each staker will get their stake of the payment.
