### ISSUE TITLE
ContractWatcher implementation

### ISSUE THREAD

**Issue by solomondefi** [solomondefi/solomon-monorepo#15]
Add implementation and tests to `src/klass/ContractWatcher.ts` based on the following criteria:

- Blockchain operations via [Ethers](https://docs.ethers.io/v5/)
  - Infura for RPC, local network for dev
    - Env: `ETHEREUM_RPC_PROVIDER_URL`
    - Local: `http://localhost:8545`
    - Testnet (staging): `https://ropsten.infura.io/v3/<infura-id>`
    - Mainnet (production): `https://infura.io/v3/<infura-id>`
  - Scan from most recently processed block to latest available block
    - No actions implemented yet, so blockchain operations are mostly placeholder
    - Placeholder code for filtering based on log events
    - Env: `ETHEREUM_START_BLOCK`
    - State:
      - Store latest processed block after scan
      - No state management set up yet, use local (sqlite3, file-based, etc) state for now. Postgres may come later
- Testing: ContractWatcher.spec.ts
  - Latest block state updated as expected after scan
  - Mocked ethers functions called as expected

**Comment by solomondefi** [comment]
Update: the issue description mentions `src/klass/ContractWatcher.ts`, but may also involve changes to `src/service/watcherService.ts` or other files, up to the implementer's discretion.

**Comment by apolkingg8** [comment]
```
Scan from most recently processed block to latest available block
```
I don't understand this section. As far as I know, the state is stored by `contract`, and we are implementing a `watcher` to watch the contract state (or event log) change. Why we need to "scan block"?

**Comment by solomondefi** [comment]
The way the blockchain works is basically an append-only log. So the state of the blockchain is stored as the total of all the blocks.
```
block1 -> block2 -> block3 -> block4 -> block5 -> latestBlock
```
When you create or interact with a contract, information about that is stored in the latest block, as well as the event logs. If your contract was created in `block2`, it means there is no relevant state in `block1` (for the Watcher, that means we don't need to scan it for logs).

The Watcher might start by scanning `block2`, and trigger actions based on events found in the logs. Then, it needs to check `block3`, block4` ... all the way to `latestBlock` to make sure all events are accounted for. Once it's up to `latestBlock`, it needs to periodically check for new blocks. If we scan every minute, there will be an average of 4 new blocks per scan.

**Comment by apolkingg8** [comment]
Thanks for your explanation, but I'm still a bit confuse about the `scan block`. As far as I know, we can get logs by `ethers.js` like that:
```typescript
let eventFilter = contract.filters.MyEvents()
let events = await contract.queryFilter(eventFilter)
```
The `scan block` action looks like automatic handled by `ethers.js`, so the `ETHEREUM_START_BLOCK` means `Contract address`?

**Comment by apolkingg8** [comment]
Besides that, why we need store the `last block state`? The `mailer`'s mission is watch the event log change, and we already have `ethers.js`'s event listener, so why we need store the state again? Just for cache?

**Comment by solomondefi** [comment]
Basically, if the `mailer` service stops for a while, we want to start from the latest scanned block, instead of reading from the first block again. This will avoid triggering duplicate events, and it will be much faster.
