### ISSUE TITLE
Cron job for blockhain processing

### ISSUE THREAD

**Issue by solomondefi-dev** [SolomonDefi/solomon-monorepo#16]
The `ContractWatcher.ts` scan function needs to be called periodically.

**Criteria**
- Cron or cron-like job runs in the application process periodically
  - Env: add var for triggering periodic job with seconds resolution
- Calls and blocks on `ContractWatcher` block scanning function
- Triggers the next job on scan complete (to avoid overlapping jobs)
- Reports errors to logfile
- Test that the job is triggered correctly (find way to avoid/mock time aspect?)

**Comment by solomondefi** [comment]
Note: instead of a cron job we may prefer to use something like this: https://infura.io/docs/ethereum/wss/eth-newFilter

Implementation of this is open ended, multiple approaches may need to be investigated.

**Comment by apolkingg8** [comment]
Due to the refactor in #15, we use event listener & filter instead of the cron job. So close this.

**Comment by solomondefi-dev** [comment]
@apolkingg8 Makes sense. Is there anything missing from 15 in order to enable this functionality? Mainly:
- Able to start scanning from a configurable block number
- Error handling/restart scan from latest block

If so, can you create another issue to track that?

**Comment by apolkingg8** [comment]
Thanks for that!

> Able to start scanning from a configurable block number

Add to #1 

> Error handling/restart scan from latest block
Reports errors to logfile

Move to #70

**Comment by solomondefi-dev** [comment]
👍
