### ISSUE TITLE
Add check generate into git pre-commit hook

### ISSUE THREAD

**Issue by apolkingg8** [SolomonDefi/solomon-monorepo#160]
The hook will do the following steps:

1. Check target files exist
2. Check source files status
3. If target file does not exist or source files status is modified, run generate script

Currently, we have the following targets:

1. Contract type (`libs/shared/util-contract`)
2. Event type (`libs/shared/util-event`)

**Comment by solomondefi-dev** [comment]
@apolkingg8 I just created #159, I will merge these later with your additional details.

**Comment by apolkingg8** [comment]
@solomondefi-dev I merged it. Close because duplicate to #159.

**Comment by solomondefi-dev** [comment]
Thanks!
