### ISSUE TITLE
Project E2E initialize

### ISSUE THREAD

**Issue by apolkingg8** [SolomonDefi/solomon-monorepo#161]
Fork from #115 
* Init e2e testing environment.
  * Run blockchain node, and deploy contracts 
* Run against full skaffold environment
* Implement basic dispute test that shows interaction between all apps
* Integrate into CI (push this to another issue if too difficult)
* Simulate server up / down quickly and check the issue about duplicate / missing events (maybe another issue)

Consider repurposing the existing blockchain watcher e2e app, since we only really need one overall e2e tests. Other tests can exist within individual apps. Updated the issue title to reflect this, and points to 5.

**Comment by beefho67** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Solomon-Tech-61445646f1ddee001380b47c/issues/SolomonDefi/solomon-monorepo/161?planning-poker) with ZenHub @apolkingg8 @solomondefi-dev

**Comment by solomondefi-dev** [comment]
It may be difficult to integrate a true e2e into Github CI without involving skaffold. My suggestion is to give it a try, but not spend too much effort on CI if it's difficult. My point vote is based on that.

**Comment by beefho67** [comment]
Hi @apolkingg8 , this one is not started yet, right? Do we stil plan to integrate it to Github CI in this issue? If not, we can create a separate issue to track it.

**Comment by apolkingg8** [comment]
`Integrate into CI (push this to another issue if too difficult)`

There is a [Service containers](https://docs.github.com/en/actions/using-containerized-services/about-service-containers) feature in GitHub action, and I think no other way to run a service in the GH action. That means, we need some new (and duplicate) Dockers to do that. I prefer pending if before we find a better way to integrate it to CI.

**Comment by beefho67** [comment]
@solomondefi-dev Per discussion with @apolkingg8 , we need #206 to work in order to wrap up this issue. I will move this issue to blocked/waiting column until #206 is fixed. Meanwhile, there is still something we can do without #206.
