### ISSUE TITLE
Handle LF / CRLF in git hook

### ISSUE THREAD

**Issue by apolkingg8** [SolomonDefi/solomon-monorepo#163]

**Comment by solomondefi-dev** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Solomon-Tech-61445646f1ddee001380b47c/issues/SolomonDefi/solomon-monorepo/163?planning-poker) with ZenHub @apolkingg8 @kelvin-wong @jtse0
