### ISSUE TITLE
MJML for email formatting

### ISSUE THREAD

**Issue by solomondefi** [solomondefi/solomon-monorepo#17]
Add [MJML](https://mjml.io/) for compiling email templates, and enable variable interpolation in the compiled emails.

Criteria:
- Add MJML template and compiled template folders
- Add `package.json` script for compiling MJML
  - Run script on `pre-commit` or even better, on saving any MJML template (not sure about VSCode vs Webstorm)
- Choose JS library for variable templating (e.g. Handlebars or EJS) that can work together with MJML
- Add Mailgun helper function that takes the path of the compiled template, variables, email recipient, email title, and text fallback
- Test the helper function triggers the mailgun request and correctly adds variables to the message

Initial example template:
```html
<mjml>
  <mj-body>
    <mj-section>
      <mj-column>

        <mj-image width="100px" src="/assets/img/logo.png"></mj-image>

        <mj-divider border-color="#2a2a2a"></mj-divider>

        <mj-text font-size="20px" color="#2a2a2a" font-family="helvetica">Chargeback request submitted</mj-text>
        <mj-text font-size="16px" color="#2a2a2a" font-family="helvetica">Your chargeback request has been committed to the blockchain, you now have {{hours}} hours to submit evidence before arbitrators make a final decision.</mj-text>
        <mj-text font-size="16px" color="#2a2a2a" font-family="helvetica">Use this form to submit evidence: {{evidence_url}}</mj-text>
        <mj-text font-size="16px" color="#2a2a2a" font-family="helvetica">You will receive a notification when evidence is successfully submitted, and when arbitration completes.</mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

This image can be used as `logo.png`:

![solomon](https://user-images.githubusercontent.com/75869471/132461234-b9dc4082-5714-42f3-8e1a-501e158543be.png)

**Comment by apolkingg8** [comment]
> Add package.json script for compiling MJML
Run script on pre-commit or even better, on saving any MJML template (not sure about VSCode vs Webstorm)

I think add into `Nx` build scripts would be better.

**Comment by apolkingg8** [comment]
About the mail content and design, I move it to #31 because I want complete the code side first.

**Comment by apolkingg8** [comment]
> Test the helper function triggers the mailgun request and correctly adds variables to the message

I think we need a `mailgun` test env for that, fork to #32 .
