### ISSUE TITLE
Simplify general staking reward

### ISSUE THREAD

**Issue by solomondefi-dev** [SolomonDefi/solomon-monorepo#177]
In the `143-juror-tiebreaker` branch, a fair but somewhat complex system for distributing staker rewards was implemented. Due to high gas costs and the goal of keeping things as simple as possible for the initial release, this should be changed to the basic strategy of letting stakers withdraw `(stake / totalStake) * rewardPool * stakeRewardModifier`, where modifier is a fixed fraction set by the admin. The initial value can be (1 / 10).

**Requirements**
- Simplify SlmStakeManager `_calculateStakeRewards`

**Notes**
- In case we want to reference the previous implementation the relevant commit hash is 70bd176d4acbf3000c52fc43ed77092b52cd4b0a

**Comment by beefho67** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Solomon-Tech-61445646f1ddee001380b47c/issues/SolomonDefi/solomon-monorepo/177?planning-poker) with ZenHub @jtse0 @solomondefi-dev
