### ISSUE TITLE
Add evidence uploader backend Dockerfile

### ISSUE THREAD

**Issue by solomondefi-dev** [SolomonDefi/solomon-monorepo#20]
Add Dockerfile  for evidence uploader backend.

**Comment by beefho67** [comment]
It complains about some gcc dependencies and so on when installing poetry. After I google for solutions and refer to https://wiki.alpinelinux.org/wiki/GCC and https://github.com/geerlingguy/JJG-Ansible-Windows/issues/28 , the poetry can be installed on the docker image.

**Comment by solomondefi-dev** [comment]
Yes, it looks a little bit more complicated than I expected. Here's one example (7 months old): https://github.com/FrederikP/python-poetry-alpine/blob/master/Dockerfile

**Comment by beefho67** [comment]
> Yes, it looks a little bit more complicated than I expected. Here's one example (7 months old): https://github.com/FrederikP/python-poetry-alpine/blob/master/Dockerfile

@solomondefi-dev Thanks. This solution works. However, it creates an image of 1.04GB. This should be ok, right?

I aslo manage to install poetry in a base alpine by 

> RUN apk add --no-cache build-base libffi-dev python3-dev
RUN pip3 install --upgrade pip
RUN pip3 install poetry

The image size is about 581MB. I can do either way but if the image size is also what we think about. We can go with the later one.
