### ISSUE TITLE
api-dispute issue

### ISSUE THREAD

**Issue by apolkingg8** [SolomonDefi/solomon-monorepo#205]
@kelvin-wong please check branch `161-deploy-contract` and run test file `apps/app-e2e/src/api-dispute.spec.ts` with jest. The test cases should all pass but `/api/events evidence.preorder.submitted` and `/api/events dispute.preorder.completed` failed. Please let me know if the test case is not correct, thanks.

**Comment by kelvin-wong** [comment]
Just checked the tests and the validation for the request, they just missed some of the validation.
https://github.com/SolomonDefi/solomon-monorepo/issues/118
