### ISSUE TITLE
Move prettier hook to pre-commit

### ISSUE THREAD

**Issue by apolkingg8** [SolomonDefi/solomon-monorepo#211]
1. Use `pnpx pretty-quick --staged` to replace `pnpx nx format:write --base=main --head=HEAD`
2. Add in `pre-commit`, not `pre-push`

**Comment by beefho67** [comment]
@apolkingg8 Is this something you are working on or you plan to work on soon? If so, can I move it to **_In Progress_** or **_Milestone backlog_** column accordingly? Thanks.
