### ISSUE TITLE
Move hardhat config to root directory

### ISSUE THREAD

**Issue by solomondefi-dev** [SolomonDefi/solomon-monorepo#214]
Currently we have two hardhat.config.ts files with duplicated contents. It should be possible to maintain a single version in the root of the project, though some reorganization or filepath updates may be required.

@jtse0 Can take a look and fill in any extra details required to make this work in the issue description?

**Comment by jtse0** [comment]
This issue just required minor updates to some paths in the hardhat and ts configs when moving the hardhat config to the root directory.  The rest of the child configs in respective app folders have been removed.
