### ISSUE TITLE
Investigate skaffold or other for deploy tooling

### ISSUE THREAD

**Issue by solomondefi-dev** [SolomonDefi/solomon-monorepo#26]
Since we already use skafffold to set up the local dev environment, it may be convenient to use for production.

List of other possibilities: TBD

**Comment by solomondefi-dev** [comment]
@kelvin-wong Maybe you can take a look at this one when other work is finished.

We could try running on Amazon EKS or DigitalOcean's k8s cluster.

**Comment by kelvin-wong** [comment]
After reviewing some of the deployment alternatives, `skaffold` could be a good enough choice for this stage. It provided the local and also deploy pipeline for developers which simplified some of the configurations. The next stage for this issue would be planning to deploy to staging and production environments.

**Comment by solomondefi-dev** [comment]
Ok, great! When you're able to, please post some issues related to getting a staging deploy set up. Placeholders are fine, we can fill in more details later.

**Comment by beefho67** [comment]
Hi @kelvin-wong, I think you've done the research, summarize results, and create issues accordingly. Based on my past experience, these already achieve what a spike ask for. Do you have anything else to highlight before we close this issue? Further technical detail, clarifications, estimations, and implementation can be tracked in the issues you created. Please let me know if it's ok to close this one. Thanks.

**Comment by kelvin-wong** [comment]
@beefho67 I think it's ok to close this one and create another one to keep track of all of the related issues.

**Comment by beefho67** [comment]
Close this one and use #193 to track relevant issues.
