### ISSUE TITLE
Evidence uploader S3 asset upload

### ISSUE THREAD

**Issue by solomondefi-dev** [SolomonDefi/solomon-monorepo#27]
Merchants and buyers (users) need to be able to upload evidence during a dispute

Update: consider implementing in a generic way that allows testing and multiple future data backends.

### Requirements
- During a dispute period, merchants and buyers can upload evidence as PNG, JPG, ZIP, TXT, or PDF files
- A way to clean up old evidence files X number of days after they're created
- The user must be authenticated and currently engaged in a chargeback, escrow, or preorder dispute. This will need to be verified on the blockchain, or via cached blockchain data.

**Comment by kelvin-wong** [comment]
@solomondefi For supporting the ZIP file, it could be better to have some extra checks on that. One of the measures I came up with is to scan through the ZIP file to see if it only contains PNG, JPG, TXT, or PDF files. What do you think?

Also, the file size should be one of the setting constants.

**Comment by solomondefi** [comment]
@kelvin-wong Yes, both scanning the zip file and file size setting are good.

We may want to limit the zip file to no folders, or a single folder level deep as well.
