### ISSUE TITLE
Set up development environment locally

### ISSUE THREAD

**Issue by beefho67** [SolomonDefi/solomon-monorepo#50]
1. Follow these two guides to set up NX development environment
https://github.com/ChoiHoldings/client-monorepo/wiki/Nx
https://github.com/SolomonDefi/solomon-monorepo/blob/main/README.md

2. Install Docker Desktop for Mac

3. Setup Skaffold

4. Any other thing that is required for a development environment to be complete and ready for testing locally

**Comment by beefho67** [comment]
I successfully run developer-docs and web-evidence by 

pnpx nx serve <app-name>

Encountered a issue when running blockchain-mailer, I think this depends on issue #56 

And I am setting up api-evidence locally.

I will skip the Skaffold for now since the configurations for Skaffold are not ready yet.

**Comment by beefho67** [comment]
Running blockchain-mailer issue will depends on #51 instead of #56.

**Comment by apolkingg8** [comment]
Open #71 for mail service launch error.

**Comment by beefho67** [comment]
![Screen Shot 2021-09-23 at 3 20 29 PM](https://user-images.githubusercontent.com/10204578/134473172-e5def8f1-45b2-49c8-b12a-188dd60b0cb4.png)

For the error installing psycopg2 (2.9.1), I found a solution from [github](https://github.com/psycopg/psycopg2/issues/1200#issuecomment-776159466). It suggests that PostgreSQL dependencies have to be installed before psycopg2-binary. After I install PostgreSQL, poetry install works well and psycopg2 can be installed. I will make a change to [README.md](https://github.com/SolomonDefi/solomon-monorepo/blob/main/apps/api-evidence/README.md) saying that PostgreSQL has to be installed before "poetry install" on Mac.

**Comment by solomondefi-dev** [comment]
Yes sorry, I missed your preview message about that. Once skaffold is set up this shouldn't be necessary unless working directly on the database.

Note that there were previously some issues regarding postgres and psycopg2-binary on Mac M1, but they may be resolved already.

**Comment by beefho67** [comment]
After psycopg2 was installed and I ran pnpx nx serve api-evidence, then I got

Cannot find module 'shelljs'
Require stack:
- /Users/ianho/git-projects/solomon-monorepo/node_modules/nx-python-fastapi/src/poetry.js
- /Users/ianho/git-projects/solomon-monorepo/node_modules/nx-python-fastapi/src/executors/serve/executor.js
- /Users/ianho/git-projects/solomon-monorepo/node_modules/@nrwl/tao/src/shared/workspace.js
- /Users/ianho/git-projects/solomon-monorepo/node_modules/@nrwl/tao/src/commands/run.js
- /Users/ianho/git-projects/solomon-monorepo/node_modules/@nrwl/tao/index.js
- /Users/ianho/git-projects/solomon-monorepo/node_modules/@nrwl/cli/lib/run-cli.js

And I did npm install shelljs and ran again, now api-evidence is working
<img width="617" alt="Screen Shot 2021-09-24 at 11 01 31 AM" src="https://user-images.githubusercontent.com/10204578/134611783-67609791-f8b9-4ac6-a879-5f52a5d68ca5.png">

The rest of work is to run blockchain-mailer and it depends on #71 to be fixed.

**Comment by solomondefi-dev** [comment]
Good catch. This is an issue with how I set up CI, you can also see the error in the CI runner here: https://github.com/SolomonDefi/solomon-monorepo/pull/49

I am waiting on that PR to complete, and will fix the shelljs issue (and CI) before merging.

**Comment by beefho67** [comment]
Docs is updated via PR https://github.com/SolomonDefi/solomon-monorepo/pull/74

#72 and #71 are fixed and closed.

pnpx nx serve blockchain-watcher --verbose is back to normal on my machine
<img width="574" alt="Screen Shot 2021-09-24 at 4 39 56 PM" src="https://user-images.githubusercontent.com/10204578/134645173-fbc1b7a0-f7c7-4caa-bd5b-d01fe69411a5.png">

**Comment by beefho67** [comment]
Based on the guideline from https://solomondefi.github.io/guide/contributing.html#pull-requests

Close https://github.com/SolomonDefi/solomon-monorepo/pull/74
