### ISSUE TITLE
When running blockchain-mailer, error of "UnhandledPromiseRejectionWarning: Error: Parameter key is required" is thrown

### ISSUE THREAD

**Issue by beefho67** [SolomonDefi/solomon-monorepo#56]
As a new comer, follow the steps described in [Solomon Monorepo](https://github.com/SolomonDefi/solomon-monorepo/blob/main/README.md) and try to run blockchain-mailer by

pnpx nx serve blockchain-mailer

It throws an error like this

![Screen Shot 2021-09-23 at 10.33.32 AM.png](https://images.zenhubusercontent.com/61416ed95cb47313cb5fcfe8/53faf99b-dd67-40f4-a629-fdb2d7e52213)

I think this requires some steps to fix the issue in a local development environment.

**Comment by apolkingg8** [comment]
It was fixed (ignored) in https://github.com/SolomonDefi/solomon-monorepo/pull/51. Mailer (or cron) service is still WIP and not ready for launch now.

**Comment by beefho67** [comment]
> It was fixed (ignored) in #51. Mailer (or cron) service is still WIP and not ready for launch now.

Thanks for the information.
