### ISSUE TITLE
Add branch name lint

### ISSUE THREAD

**Issue by apolkingg8** [SolomonDefi/solomon-monorepo#79]
The CI will run fail if we use uppercase in the branch name. (ex: https://github.com/SolomonDefi/solomon-monorepo/runs/3697063931?check_suite_focus=true#step:5:101)

Consider add a lint or add a branch name rule in the document.

**Comment by solomondefi-dev** [comment]
I think we can add something to `.husky/pre-commit` such as:

```
#!/usr/bin/env bash
local_branch_name="$(git rev-parse --abbrev-ref HEAD)"

valid_branch_regex='^([a-z0-9\-_]+)$'

message="Invalid branch name. Branch names must match: $valid_branch_regex. Please rename the branch and try again."

if [[ ! $local_branch_name =~ $valid_branch_regex ]]; then
    echo "$message"
    exit 1
fi

exit 0
```
