### ISSUE TITLE
Commit format convention

### ISSUE THREAD

**Issue by solomondefi** [solomondefi/solomon-monorepo#8]
Add `commit-msg` checks for message format. This can be done with a custom regex, there's probably no need to import a package.

### Tasks
- Implement commit message check for `<scope> [<project>]: <short-summary> #<issue-number>`
- Add Husky for `commit-msg` trigger
- Add releaser via [conventional-github-releaser](https://www.npmjs.com/package/conventional-github-releaser) or similar

**Comment by apolkingg8** [comment]
I find [semantic-release](https://github.com/semantic-release/semantic-release) and [semantic-release-gitmoji](https://github.com/momocow/semantic-release-gitmoji), looks good but I need some time to survey them. It's my first time to setup something like that.

**Comment by solomondefi** [comment]
No problem, it's actually not that urgent. We can merge your PR first and move the automated release task to a new issue.

**Comment by apolkingg8** [comment]
No worry, I think I can complete it with just one more day :)

**Comment by apolkingg8** [comment]
@solomondefi Please set a `GH_TOKEN` for [semantic release](https://semantic-release.gitbook.io/semantic-release/usage/ci-configuration#authentication)

**Comment by solomondefi** [comment]
Will do. Migrating docs is about halfway done, which will have some CI changes too, so I'll merge this after and make sure everything works together.

**Comment by solomondefi** [comment]
Closed in #7
