### ISSUE TITLE
pnpm issue with TypeChain

### ISSUE THREAD

**Issue by apolkingg8** [SolomonDefi/solomon-monorepo#83]
```
"resolutions": {
  "typechain": "5.1.2",
  "@typechain/ethers-v5": "7.1.2",
  "@typechain/hardhat": "2.3.0"
},
```
Currently, I add this in `package.json` to resolve the issue https://github.com/dethcrypto/TypeChain/issues/401 . I guess it's an issue about `pnpm` because `Yarn` works fine, but I don't have a minimal reproduce repo yet. Track it here until it works without `resolutions`.

**Comment by apolkingg8** [comment]
Close it since it works fine without `resolutions` now.

**Comment by solomondefi-dev** [comment]
👍
