### ISSUE TITLE
Watcher webhook strategy

### ISSUE THREAD

**Issue by solomondefi-dev** [SolomonDefi/solomon-monorepo#93]
We need to provide webhooks to the `dispute` app so it can record contract events in order to provide an API for convenient user access.

- Determine a convenient way to register webhooks. If it can be simple and generic (e.g. JSON description of contract address and webhook address) that's great, but we may need a custom function per hook type.
- Webhook data is signed. there should be common solutions for this

This issue will require collaboration with the corresponding `dispute` app issue. The deliverable is a working "dummy" webhook that sends signed data of the form:
```
{
  "type": <string>
}
```
...to a registered endpoint.

**Comment by beefho67** [comment]
- a type of event, not necessary to be connected to another issue
- @samatechtw Please share an example of signing
- These types of webhooks are internal for now. We don't need public interface for now.

**Comment by solomondefi-dev** [comment]
@kelvin-wong Here is a javascript example of signing:
```
import crypto from 'crypto';

const originalUrl = 'https://example.com?param1=X&param2=Y';

const signature = crypto
  .createHmac('sha256', SECRET_KEY)
  .update(new URL(originalUrl).search)
  .digest('base64');

const urlWithSignature = `${originalUrl}&signature=${encodeURIComponent(signature)}`;
```
This example is specifically for signing a GET URL request with parameters, but a similar process can be followed for POST requests. The difference is that including the signature in the payload doesn't work, so for a POST request with data we need to include the signature in an authorization header instead. We could follow something like this: https://www.alibabacloud.com/help/doc-detail/31951.htm
